# OTA update configuration

# GitHub repository hosting releases
GITHUB_REPO="s57-dev/rdk-monorepo-build"

# Substring to match the release asset filename (the .swu package zip)
SWU_ASSET="rpi-package-swupdate"

# SWUpdate hardware compatibility string
#SWUPDATE_HW="raspberrypi4-64-rdke:1.0"
