# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rdk-optional"
BBFILE_PATTERN_rdk-optional := "^${LAYERDIR}/"
BBFILE_PRIORITY_rdk-optional = "8"

LAYERDEPENDS_rdk-optional = "core swupdate"
LAYERSERIES_COMPAT_rdk-optional = "kirkstone"
